export const breeds = [
"Labrador Retriever", 
"German Shepherd", 
"Golden Retriever", 
"Bulldog", 
"Poodle", 
"Beagle", 
"Yorkshire Terrier", 
"Boxer", 
"Dachshund", 
"Siberian Husky", 
"Rottweiler", 
"Shih Tzu", 
"Great Dane", 
"Pomeranian", 
"French Bulldog", 
"Border Collie", 
"Australian Shepherd", 
"Doberman Pinscher", 
"Cocker Spaniel", 
"Chihuahua", 
"Poodle",
]